### ISSUE TITLE
QRcode scanner sometimes is rotated

### ISSUE THREAD

**Issue by riki-dexter** [yannickl/QRCodeReader.swift#123]
Both scanning in preview mode and in modal action sometimes camera frame is 90 degrees rotated

**Comment by yannickl** [comment]
I'll investigate that. That you for the repport! 👍

**Comment by CIAlexanderAkimov** [comment]
Here is a temporary workaround:

present(readerVC, animated: true)
DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
    NotificationCenter.default.post(name: .UIDeviceOrientationDidChange, object: nil)
}

Investigated briefly in my app with landscape only orientations supported:

On the 1st call to orientationDidChange() in QRCodeReaderView sometimes:
- reader.previewLayer is instantiated, 
  but 
- reader.previewLayer.connection is nil

So the condition "if let connection = reader?.previewLayer.connection, connection.isVideoOrientationSupported {" is not passed.
And the user should rotate the device in order to enforce orientationDidChange() to be called once again.

**Comment by yannickl** [comment]
@CIAlexanderAkimov thank you, I'll check that in the w-e.
