### ISSUE TITLE
just inquiry,,, not really an issue -> more configuration or function

### ISSUE THREAD

**Issue by zuyao1988** [yannickl/QRCodeReader.swift#45]
Hi, I'm new to swift n xcode..

Thx for the qrcodereader pod and it works perfectly fine.

My question is, if I want to use front camera as default, or remove "cancel" words...
1. should I edit the library?
2. or how can I know what's function did the library allow me to configure, e.g: reader.useFrontCamera = true

**Comment by yannickl** [comment]
Hi, sorry for the late.

You can call the `reader.switchDeviceInput()` method of the `QRCodeReader`. For the moment if you need access to the reader of the view controller you need to pass it during the initialisation. But I'll update the library to make it public in order to make the manipulation easier.

**Comment by zuyao1988** [comment]
thanks for reply!
I've configure functions for my need for now and thanks for the library!

**Comment by yannickl** [comment]
Great! :+1:
