### ISSUE TITLE
Shouldn't `didSwitchCamera` be optional

### ISSUE THREAD

**Issue by alimoeeny** [yannickl/QRCodeReader.swift#87]
Unless I am much mistaken, implementing `QRCodeReaderViewControllerDelegate` requires implementing `public func reader(_ reader: QRCodeReaderViewController, didSwitchCamera newCaptureDevice: AVCaptureDeviceInput)`

Shouldn't this be an optional method on the protocol definition? I mean what is the reason to make it required.

**Comment by yannickl** [comment]
Hi @alimoeeny,

The `func reader(_ reader: QRCodeReaderViewController, didSwitchCamera newCaptureDevice: AVCaptureDeviceInput)` is already "optional" because there is a [default implementation](https://github.com/yannickl/QRCodeReader.swift/blob/d6b85ec9b4fafa844921a00e990d6465ad564fb9/Sources/QRCodeReaderViewControllerDelegate.swift#L65)

The compiler should not ask you to implement this method.

**Comment by alimoeeny** [comment]
thanks @yannickl , mmm, for some reason it does, that is how I noticed it, something must have gone wrong. will looks into it later then. thanks
